### ISSUE TITLE
Library Error When Generating Model with Cadquery as an engine

### ISSUE THREAD

**Issue by Silverdev2482** [bullwinkle3000/dactyl-keyboard#12]
I have been struggling to get this model to generate. I am using an ubuntu vm. I accidentally tried the windows instructions but now I ran the conda.sh and it replace dactyl-keyboard I think. I should say I have little to no experience with python. after changing the engine to cadquery in the run_config.json I get this error:
`(dactyl-keyboard) silverdev2482@silverdev2482-Standard-PC-Q35-ICH9-2009:~/dactyl-keyboard$ python src/dactyl_manuform.py 
>>> Using config run_config.json on Git branch wilder
Found Current Engine in Config = cadquery
Traceback (most recent call last):
  File "src/dactyl_manuform.py", line 2452, in <module>
    make_dactyl()
  File "src/dactyl_manuform.py", line 248, in make_dactyl
    globals().update(importlib.import_module("helpers_cadquery").__dict__)
  File "/home/silverdev2482/anaconda3/envs/dactyl-keyboard/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/silverdev2482/dactyl-keyboard/src/helpers_cadquery.py", line 1, in <module>
    import cadquery as cq
  File "/home/silverdev2482/anaconda3/envs/dactyl-keyboard/lib/python3.8/site-packages/cadquery/__init__.py", line 10, in <module>
    from .occ_impl.geom import Plane, BoundBox, Vector, Matrix, Location
  File "/home/silverdev2482/anaconda3/envs/dactyl-keyboard/lib/python3.8/site-packages/cadquery/occ_impl/geom.py", line 5, in <module>
    from OCP.gp import (
ImportError: libTKIVtk.so.7.7: cannot open shared object file: No such file or directory
`
I assume this means I'm missing libraries but unless I'm stupid (which could be the case) I haven't seen anything about installing libraries other than the conda.sh. I tried install the occt-draw and occt-misc from apt but that didn't change anything. What do I need to do to get these libraries working?

**Comment by C-Flatla** [comment]
I was running into this issue as well, but I think I found a solution 😄. In the `conda.sh` setup script, `occt` needs to be installed alongside `cadquery`.

Instead of:
```
conda install -c conda-forge -c cadquery cadquery=master -y
```

I found this to work:
```
conda install -c conda-forge cadquery occt=7.7.0 -y
```
(found this from this issue in the cadquery repo https://github.com/CadQuery/cadquery/issues/1304)
