### ISSUE TITLE
Error when specifying any OLED other than null

### ISSUE THREAD

**Issue by Trecoolius** [bullwinkle3000/dactyl-keyboard#17]
Whether I use "SLIDING," "UNDERCUT" or "CLIP," I get an error about an undefined variable:

```
(dactyl-keyboard) C:\Users\xxx\dactyl-keyboard>python src/dactyl_manuform.py
>>> Using config run_config.json on Git branch wilder
Found Current Engine in Config = solid
DEFAULT  built
model_side()right
thumb()
default thumb_connectors()
case_walls()
back_wall()
left_wall()
Traceback (most recent call last):
  File "C:\Users\xxx\dactyl-keyboard\src\dactyl_manuform.py", line 2619, in <module>
    make_dactyl()
  File "C:\Users\xxx\dactyl-keyboard\src\dactyl_manuform.py", line 2614, in make_dactyl
    run()
  File "C:\Users\xxx\dactyl-keyboard\src\dactyl_manuform.py", line 2506, in run
    mod_r, walls_r = model_side(side="right")
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\dactyl-keyboard\src\dactyl_manuform.py", line 2250, in model_side
    walls_shape = case_walls(side=side)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\dactyl-keyboard\src\dactyl_manuform.py", line 1296, in case_walls
    left_wall(side=side),
    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\dactyl-keyboard\src\dactyl_manuform.py", line 1204, in left_wall
    shape = union([wall_brace(
                   ^^^^^^^^^^^
  File "C:\Users\xxx\dactyl-keyboard\src\dactyl_manuform.py", line 1117, in wall_brace
    hulls.append(place2(post2))
                 ^^^^^^^^^^^^^
  File "C:\Users\xxx\dactyl-keyboard\src\dactyl_manuform.py", line 1206, in <lambda>
    (lambda sh: left_key_place(sh, 0, 1, side=side)), 0, 1, web_post(),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\dactyl-keyboard\src\dactyl_manuform.py", line 1067, in left_key_place
    pos = left_key_position(row, direction, low_corner=low_corner, side=side)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\dactyl-keyboard\src\dactyl_manuform.py", line 1036, in left_key_position
    wall_x_offsets = get_left_wall_offsets(side)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\dactyl-keyboard\src\dactyl_manuform.py", line 108, in get_left_wall_offsets
    left_wall_x_offset = oled_left_wall_x_offset_override
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'oled_left_wall_x_offset_override' is not defined. Did you mean: 'tbiw_left_wall_x_offset_override'?
```

The only way to successfully generate any geometry is to use null.

**Comment by MoritzPerschke** [comment]
Did you get this working somehow? I've been looking through the file trying to find the error for the past hour and didn't get anywhere
