### ISSUE TITLE
docker images do not contain the git module

### ISSUE THREAD

**Issue by birdybro** [bullwinkle3000/dactyl-keyboard#19]
Fresh docker for windows install, fresh setup with the batch file first time and I receive the following errors when trying to run DM-release-build and DM-run

DM-release-build:
```
2024-07-19 15:19:46 Traceback (most recent call last):
2024-07-19 15:19:46   File "/app/src/model_builder.py", line 108, in <module>
2024-07-19 15:19:46     build_release(base, configurations, ENGINES)
2024-07-19 15:19:46   File "/app/src/model_builder.py", line 95, in build_release
2024-07-19 15:19:46     import dactyl_manuform as dactyl_manuform
2024-07-19 15:19:46   File "/app/src/dactyl_manuform.py", line 11, in <module>
2024-07-19 15:19:46     import git
2024-07-19 15:19:46 ModuleNotFoundError: No module named 'git'
```

DM-run:
```
2024-07-19 15:19:45 Traceback (most recent call last):
2024-07-19 15:19:45   File "/app/src/dactyl_manuform.py", line 11, in <module>
2024-07-19 15:19:45     import git
2024-07-19 15:19:45 ModuleNotFoundError: No module named 'git'
```

**Comment by phantum29** [comment]
Did you ever solve this? The master build seems to (mostly) work aside from a numpy error for bool8. A quick test of master build dockerfile and env files in place of what's included in this release does not solve the issue.

Edit: solved for this. Had to edit the Dockerfile and add the line `gitpython=3.1.43 \` after `numpy=1 \` however now I run into more errors. I had to make sure the dir was sync'd with the repo to get rid of some other errors about git source. I made a new issue request.
